spring.application.name=abm.manager
spring.banner.location=classpath:banner.txt
# Configuracion de la Base de Datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sales
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Configuracion del servidor Tomacat
server.port=8035
server.servlet.context-path=/abm-manager/api
